"""Infrastructure-neutral interfaces; DTO semantics are defined in docs/spec."""
from __future__ import annotations
from typing import Any, Protocol
from pathlib import Path

class DataDirectoryPort(Protocol):
    """Catalog only; does not certify immutable analysis input (SR05)."""
    def available(self) -> bool: ...
    def list_snapshots(self) -> list[str]: ...
    def load(self, snapshot_id: str) -> dict: ...
    def summary(self, snapshot_id: str) -> dict: ...
    def validate(self, snapshot_id: str) -> dict: ...

class AnalysisConfigurationPort(Protocol):
    """Legacy analysis environment, explicitly injected until ARC11 migration."""
    def factor_snapshot_dir(self, dataset: dict[str, Any]) -> Path: ...
    def annualisation(self) -> tuple[int, str]: ...

class FactorInputPort(Protocol):
    """Frozen market input; numeric grids and semantic basis, no engine objects."""
    def calendar(self) -> list[str]: ...
    def read(self, dates: list[str], instruments: list[str], horizons: tuple[int, ...]) -> dict: ...

class FactorDataPort(Protocol):
    def resolve(self, dataset: dict, calendar_id: str) -> FactorInputPort: ...
