"""Infrastructure-neutral interfaces; DTO semantics are defined in docs/spec."""
from __future__ import annotations
from typing import Any, Protocol

class ResultRepository(Protocol):
    def publish(self, source_instance_id: str, external_id: str, adapter_version: str,
                package: dict[str, Any]) -> dict[str, Any]: ...

    def list_runs(self, limit: int = 20, cursor: str | None = None) -> dict[str, Any]: ...

    def get_run(self, run_id: str) -> dict[str, Any] | None: ...

    def list_revisions(self, run_id: str) -> list[dict[str, Any]]: ...

    def list_revisions_page(self, run_id: str, limit: int = 20, cursor: str | None = None) -> dict[str, Any]: ...

    def get_revision(self, run_id: str, revision_id: str | None = None) -> dict[str, Any] | None: ...

    def health(self) -> dict[str, Any]: ...


class FactorRepository(Protocol):
    def publish_factor(self, identity: dict[str, Any], panel: dict[str, Any]) -> dict[str, Any]: ...

    def list_factors(self) -> list[dict[str, Any]]: ...

    def get_factor(self, factor_id: str) -> dict[str, Any] | None: ...

    def list_factor_panels(self, factor_id: str) -> list[dict[str, Any]]: ...

    def get_factor_panel(self, factor_id: str, panel_id: str | None = None) -> dict[str, Any] | None: ...


class AttemptRepository(Protocol):
    def health(self) -> dict[str, Any]: ...

    def create_attempt(self, record: dict[str, Any], *,
                       max_concurrent: int | None = None) -> tuple[dict[str, Any], bool]: ...

    def get_attempt(self, attempt_id: str) -> dict[str, Any] | None: ...

    def find_attempt_by_key(self, idempotency_key: str) -> dict[str, Any] | None: ...

    def update_attempt(self, attempt_id: str, **fields: Any) -> dict[str, Any] | None: ...

    def list_attempts(self, limit: int = 20, cursor: str | None = None) -> dict[str, Any]: ...

    def list_open_attempts(self, limit: int = 100) -> list[dict[str, Any]]: ...

    def reserve_agent_budget(self, *, policy_revision: str, scope: str, kind: str,
                             limit: int, amount: int = 1) -> dict[str, Any]: ...

    def agent_budget_rows(self, policy_revision: str) -> list[dict[str, Any]]: ...

    def record_agent_budget(self, *, policy_revision: str, scope: str, kind: str, limit: int,
                            used: int) -> dict[str, Any]: ...

    def record_import(self, record: dict[str, Any]) -> dict[str, Any]: ...

    def latest_import(self, attempt_id: str) -> dict[str, Any] | None: ...

    def list_imports(self, attempt_id: str | None = None, limit: int = 20) -> list[dict[str, Any]]: ...

    def attempt_stats(self, window_seconds: int = 86400) -> dict[str, Any]: ...


class WorkbenchRepository(ResultRepository, FactorRepository, AttemptRepository, Protocol):
    """Compatibility aggregate; dedicated services use narrower ports."""
